// DowgNut seed data — shared by `prisma/seed.ts` and the runtime
// auto-seed (`src/lib/ensure-ready.ts`) so Vercel cold starts reseed the
// ephemeral SQLite DB automatically.
// EVERY DONUT HAS A 100% UNIQUE IMAGE ASSET WITH ZERO DUPLICATES.

export type SeedDonut = {
  name: string;
  description: string;
  price: number;
  type: "classic" | "sprinkled" | "stuffed" | "specialty" | "savory";
  imgUrl: string;
  tags: string; // comma-separated
  rating: number;
  calories: number;
  sugar: number;
  fat: number;
  stock: number;
  featured: boolean;
};


export const SEED_DONUTS: SeedDonut[] = [
  // ── Classic (8 Unique Donuts) ──────────────────────────────
  {
    name: "Classic Glazed",
    description:
      "The OG ring donut, hand-dipped in a thin golden vanilla glaze that crackles with every bite.",
    price: 3.5,
    type: "classic",
    imgUrl: "/brand/donuts/donut_classic1.png",
    tags: "glazed,vanilla,classic",
    rating: 4.9,
    calories: 220,
    sugar: 10,
    fat: 8,
    stock: 60,
    featured: true,
  },
  {
    name: "Chocolate Cake Classic",
    description:
      "Dense old-fashioned chocolate cake donut with a cocoa-rich crumb and a hint of dark espresso glaze.",
    price: 3.9,
    type: "classic",
    imgUrl: "/brand/donuts/donut_classic2.png",
    tags: "chocolate,cake,classic",
    rating: 4.7,
    calories: 290,
    sugar: 13,
    fat: 10,
    stock: 50,
    featured: false,
  },
  {
    name: "Maple Glaze Ring",
    description:
      "Smoky Canadian maple glaze crowned with rich caramelised golden glaze over soft yeast dough.",
    price: 4.2,
    type: "classic",
    imgUrl: "/brand/donuts/donut_classic3.png",
    tags: "maple,glazed,classic",
    rating: 4.8,
    calories: 320,
    sugar: 15,
    fat: 11,
    stock: 35,
    featured: true,
  },
  {
    name: "Powdered Sugar Donut",
    description:
      "Pillow-soft yeast donut rolled in a snowdrift of superfine powdered sugar. Simple, comforting bliss.",
    price: 3.2,
    type: "classic",
    imgUrl: "/brand/donuts/donut_classic4.png",
    tags: "powdered,sugar,classic",
    rating: 4.5,
    calories: 240,
    sugar: 11,
    fat: 8,
    stock: 70,
    featured: false,
  },
  {
    name: "Cinnamon Sugar Twist",
    description:
      "Hand-twisted golden dough dusted generously in aromatic Ceylon cinnamon sugar with a tender pull-apart crumb.",
    price: 3.8,
    type: "classic",
    imgUrl: "/brand/donuts/donut_classic5.png",
    tags: "cinnamon,sugar,classic",
    rating: 4.6,
    calories: 260,
    sugar: 12,
    fat: 9,
    stock: 55,
    featured: false,
  },
  {
    name: "Old-Fashioned Sour Cream",
    description:
      "Traditional craggy cake donut with a crispy exterior, cakey center, and a thin vanilla milk glaze.",
    price: 4.0,
    type: "classic",
    imgUrl: "/brand/donuts/donut_classic6.png",
    tags: "sour cream,cake,classic",
    rating: 4.6,
    calories: 280,
    sugar: 12,
    fat: 10,
    stock: 45,
    featured: false,
  },
  {
    name: "Toasted Coconut Glaze",
    description:
      "Vanilla glazed ring coated in freshly toasted organic golden coconut flakes for an irresistible crunch.",
    price: 4.2,
    type: "classic",
    imgUrl: "/brand/donuts/toasted-coconut.png",
    tags: "coconut,toasted,classic",
    rating: 4.7,
    calories: 310,
    sugar: 14,
    fat: 12,
    stock: 40,
    featured: false,
  },
  {
    name: "Hainanese Kopi-O Glaze",
    description:
      "Robust dark roast Malaysian kopi-o glaze with caramelized sugar crackle — bold morning energy.",
    price: 4.5,
    type: "classic",
    imgUrl: "/brand/donuts/donut_classic8.png",
    tags: "kopi,coffee,malaysian,classic",
    rating: 4.8,
    calories: 270,
    sugar: 11,
    fat: 9,
    stock: 50,
    featured: true,
  },

  // ── Sprinkled (6 Unique Donuts) ─────────────────────────────
  {
    name: "Rainbow Birthday Sprinkle",
    description:
      "Strawberry pink frosting smothered in cheerful rainbow jimmies — the life of every party!",
    price: 4.2,
    type: "sprinkled",
    imgUrl: "/brand/donuts/donut_sprinkled1.png",
    tags: "rainbow,sprinkled,strawberry",
    rating: 4.9,
    calories: 280,
    sugar: 13,
    fat: 10,
    stock: 65,
    featured: true,
  },
  {
    name: "Chocolate Sprinkle Bomb",
    description:
      "Velvety dark chocolate icing under a rainbow sprinkle blast. Maximum crunch, maximum cocoa indulgence.",
    price: 4.5,
    type: "sprinkled",
    imgUrl: "/brand/donuts/donut_sprinkled3.png",
    tags: "chocolate,sprinkled,cocoa",
    rating: 4.8,
    calories: 300,
    sugar: 14,
    fat: 11,
    stock: 60,
    featured: false,
  },
  {
    name: "Strawberry Funfetti",
    description:
      "Vibrant strawberry milkshake glaze with confetti pearls baked right into the fluffy dough.",
    price: 4.4,
    type: "sprinkled",
    imgUrl: "/brand/donuts/donut_sprinkled4.png",
    tags: "strawberry,sprinkled,funfetti",
    rating: 4.7,
    calories: 290,
    sugar: 13,
    fat: 10,
    stock: 50,
    featured: false,
  },
  {
    name: "Vanilla Bean Jimmie",
    description:
      "Madagascar vanilla glaze topped with rich dark chocolate vermicelli sprinkles for the ultimate crunch.",
    price: 4.2,
    type: "sprinkled",
    imgUrl: "/brand/donuts/donut_sprinkled2.png",
    tags: "vanilla,sprinkled,chocolate",
    rating: 4.5,
    calories: 270,
    sugar: 12,
    fat: 9,
    stock: 70,
    featured: false,
  },
  {
    name: "Confetti Fiesta Sparkle",
    description:
      "Lemony bright glaze loaded with sparkling multi-colored sugar crystals and confetti jimmies.",
    price: 4.6,
    type: "sprinkled",
    imgUrl: "/brand/donuts/confetti-fiesta.png",
    tags: "confetti,sprinkled,fiesta",
    rating: 4.7,
    calories: 310,
    sugar: 15,
    fat: 11,
    stock: 45,
    featured: false,
  },
  {
    name: "Matcha White Choco Sprinkle",
    description:
      "Uji matcha green tea glaze topped with delicate white chocolate sprinkle pearls — smooth & earthy.",
    price: 4.8,
    type: "sprinkled",
    imgUrl: "/brand/donuts/matcha-white-choco.png",
    tags: "matcha,white chocolate,sprinkled,specialty",
    rating: 4.8,
    calories: 290,
    sugar: 12,
    fat: 10,
    stock: 35,
    featured: true,
  },

  // ── Stuffed (8 Unique Donuts) ───────────────────────────────
  {
    name: "Boston Cream Bomb",
    description:
      "Pillow yeast donut bursting with silky Bavarian vanilla custard, dipped in glossy dark chocolate ganache.",
    price: 4.9,
    type: "stuffed",
    imgUrl: "/brand/donuts/donut_stuffed1.png",
    tags: "cream,stuffed,chocolate,custard",
    rating: 4.9,
    calories: 380,
    sugar: 17,
    fat: 13,
    stock: 45,
    featured: true,
  },
  {
    name: "Raspberry Jelly Burst",
    description:
      "Brimming with tart organic raspberry jam that oozes on the first bite, finished in a dusting of sugar.",
    price: 4.5,
    type: "stuffed",
    imgUrl: "/brand/donuts/donut_stuffed2.png",
    tags: "jelly,stuffed,raspberry",
    rating: 4.7,
    calories: 320,
    sugar: 14,
    fat: 11,
    stock: 55,
    featured: false,
  },
  {
    name: "Cookies & Cream Core",
    description:
      "Stuffed with crushed Oreo whipped cream and topped with white chocolate cookie crumble glaze.",
    price: 4.9,
    type: "stuffed",
    imgUrl: "/brand/donuts/donut_stuffed3.png",
    tags: "cookies,cream,stuffed,oreo",
    rating: 4.9,
    calories: 420,
    sugar: 19,
    fat: 15,
    stock: 40,
    featured: true,
  },
  {
    name: "Lemon Curd Pocket",
    description:
      "Bright, zesty Meyer lemon curd piped into a fluffy yeast shell, finished with a crystalline citrus glaze.",
    price: 4.5,
    type: "stuffed",
    imgUrl: "/brand/donuts/donut_stuffed4.png",
    tags: "lemon,stuffed,curd,citrus",
    rating: 4.6,
    calories: 300,
    sugar: 14,
    fat: 11,
    stock: 50,
    featured: false,
  },
  {
    name: "Salted Caramel Cloud",
    description:
      "Filled with rich dulce de leche caramel cream, drizzled with burnt caramel and flaky Cornish sea salt.",
    price: 4.8,
    type: "stuffed",
    imgUrl: "/brand/donuts/donut_stuffed5.png",
    tags: "caramel,stuffed,salted,sea salt",
    rating: 4.8,
    calories: 410,
    sugar: 18,
    fat: 14,
    stock: 45,
    featured: false,
  },
  {
    name: "Nutella Hazelnut Lava",
    description:
      "Molten Italian hazelnut cocoa spread overflowing from the core, crowned with roasted chopped hazelnuts.",
    price: 5.2,
    type: "stuffed",
    imgUrl: "/brand/donuts/donut_stuffed6.png",
    tags: "nutella,hazelnut,chocolate,stuffed",
    rating: 4.9,
    calories: 440,
    sugar: 20,
    fat: 16,
    stock: 35,
    featured: true,
  },
  {
    name: "Blueberry Cheesecake Fill",
    description:
      "New York style cream cheese filling paired with wild blueberry coulis inside a golden brioche donut.",
    price: 4.9,
    type: "stuffed",
    imgUrl: "/brand/donuts/blueberry-cheesecake.png",
    tags: "blueberry,cheesecake,cream cheese,stuffed",
    rating: 4.8,
    calories: 390,
    sugar: 16,
    fat: 14,
    stock: 35,
    featured: false,
  },
  {
    name: "Strawberries & Cream Stuffed",
    description:
      "Fresh strawberry compote layered with sweet Chantilly cream, finished with powdered sugar & freeze-dried berry dusting.",
    price: 4.9,
    type: "stuffed",
    imgUrl: "/brand/donuts/donut_stuffed8.png",
    tags: "strawberry,cream,chantilly,stuffed",
    rating: 4.8,
    calories: 360,
    sugar: 15,
    fat: 12,
    stock: 40,
    featured: false,
  },

  // ── 🇲🇾 Malaysian Signature Specials (6 Dedicated 3D Flavor-Swap Assets) ─────────
  {
    name: "Pandan Gula Melaka",
    description:
      "Aromatic pandan glaze infused with genuine coconut santan and drizzled with smoked Melaka palm sugar syrup.",
    price: 4.9,
    type: "specialty",
    imgUrl: "/brand/donuts/pandan-gula-melaka.png",
    tags: "pandan,gula melaka,malaysian,signature",
    rating: 5.0,
    calories: 310,
    sugar: 15,
    fat: 11,
    stock: 50,
    featured: true,
  },
  {
    name: "Teh Tarik Kaw Glaze",
    description:
      "Rich frothy pulled-tea glaze with condensed milk drizzle — tastes just like your favourite mamak teh tarik kaw!",
    price: 4.8,
    type: "specialty",
    imgUrl: "/brand/donuts/teh-tarik-kaw.png",
    tags: "teh tarik,condensed milk,malaysian,specialty",
    rating: 4.9,
    calories: 330,
    sugar: 16,
    fat: 12,
    stock: 45,
    featured: true,
  },
  {
    name: "Musang King Durian Bomb",
    description:
      "Stuffed with 100% pure Raub Musang King durian custard — decadent, ultra-creamy, and royally aromatic.",
    price: 6.5,
    type: "specialty",
    imgUrl: "/brand/donuts/musang-king-durian.png",
    tags: "durian,musang king,creamy,malaysian,luxury",
    rating: 4.9,
    calories: 420,
    sugar: 16,
    fat: 18,
    stock: 30,
    featured: true,
  },
  {
    name: "Cameron Strawberry Drip",
    description:
      "Juicy Cameron Highlands strawberry glaze with a vibrant graffiti drip pattern and crispy ruby pearls.",
    price: 4.8,
    type: "specialty",
    imgUrl: "/brand/donuts/donut_classic7.png",
    tags: "cameron,strawberry,drip,malaysian",
    rating: 4.8,
    calories: 300,
    sugar: 14,
    fat: 10,
    stock: 40,
    featured: false,
  },
  {
    name: "Ipoh White Coffee Glaze",
    description:
      "Roasted Ipoh white coffee reduction glaze with a silky foam drizzle and caramelized biscuit crumble.",
    price: 4.8,
    type: "specialty",
    imgUrl: "/brand/donuts/ipoh-white-coffee.png",
    tags: "coffee,ipoh,white coffee,malaysian",
    rating: 4.8,
    calories: 320,
    sugar: 13,
    fat: 11,
    stock: 40,
    featured: false,
  },
  {
    name: "Teh Tarik Classic Foam",
    description:
      "A lighter milk tea glazed ring donut with velvety condensed milk frosting and roasted Ceylon tea dust.",
    price: 4.5,
    type: "specialty",
    imgUrl: "/brand/donuts/teh-tarik-foam.png",
    tags: "teh tarik,tea,classic,malaysian",
    rating: 4.7,
    calories: 290,
    sugar: 12,
    fat: 10,
    stock: 45,
    featured: false,
  },
];
